# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlacesQgis
                                 A QGIS plugin
 this plugin downloads geotagged reviews from google places API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-04
        copyright            : (C) 2022 by Arka
        email                : arkaprava.mail@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlacesQgis class from file PlacesQgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .places_qgis import PlacesQgis
    return PlacesQgis(iface)
